[book]
authors = ["Jorge Esteban Quilcate Otoya"]
language = "es"
multilingual = false
src = "src"
title = "Constituciones Poliíticas del Perú"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/jeqo/peru-constitucion"
git-repository-icon = "fa-github"
site-url = "https://jeqo.github.io/peru-constitucion/"
additional-css = ["custom/style.css"]
additional-js = ["custom/sidebar.js"]
google-analytics = "UA-49047812-4"